### ISSUE TITLE
[M2] Chenyang Functions + Tests

### ISSUE THREAD

**Issue by robindhillon1** [UBC-MDS/StockSignals#22]
Create the following functions and their corresponding 3 tests:

upper_band, lower_band = get_bbands(stock_ticker)
plot_bbands(stock_ticker, upper_band, lower_band)

**Comment by robindhillon1** [comment]
Specifically, the `get_bbands` should return a dataframe. Then, `plot_bbands` calls the `get_bbands` function to plot the data.

**Comment by RussDim** [comment]
Done
