### ISSUE TITLE
[M1] Deliverables

### ISSUE THREAD

**Issue by RussDim** [UBC-MDS/StockSignals#3]
Robin:
compute 200-day moving average
plot stock price vs 200-day moving average
Peng:
compute 10 and 20 day moving average
Plot stock price vs 10 and 20 day moving average
Dudu
Compute lower and upper bound of 2 std deviations
Plot stock price vs the upper and lower band
Ruslan
Review everything and finalize submission

**Comment by pengzh313** [comment]
I have created two .py files (with docstring only) to compute 10 and 20 day moving average and plot stock price vs 10 and 20 day moving average.

Please review the pull request.

For collaboration purposes (to minimize merger conflicts in the future), I think we can create separate .py files for each function, then we can combine all together at the end if we want.

**Comment by robindhillon1** [comment]
Done.

**Comment by RussDim** [comment]
Work completed
