### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/StockSignals#45]
**Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
 We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

## 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}
- Some functions aren't passing the unit tests. -  **accuracy -20** (How to discount points? 20 points will be discounted if all the test are failing. Then it will be proportional, for example if they have 10 test and 1 is failing, you will discount -2 points)

**Comment:**
I have been trying to run the test of your package and I have realized that is not possible. It seems that you have never added to the config file, pyproject.toml , your package dependencies. This is important! You need to use the command poetry add and include all your package dependencies to pyproject.toml and then poetry install.
If you push this to PyPI or TestPypi the package as it is not going to work for your users, as the dependencies are never going to be loaded.
Your tests are not working for the same reason, that is why I have to discount -20 points.
What I recommend you is to go to an OH to fix this. Of course, I am here to solve. any other question you may have. 
This section walks you through how to include dependencies (https://py-pkgs.org/03-how-to-package-a-python#adding-dependencies-to-your-package)

#### 1. Create project structure for the R project
rubric={mechanics:20}

- The `README.md` doesn't include a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset) - **mechanics -2**.   
 **Comment:** Should include short description of datasets that are being downloaded from `get_data`.

## 4. R package function specifications
rubric={quality:10}

## 5. Specific expectations for this milestone are:
rubric={mechanics:10}

## 6. Submission instructions
rubric={mechanics:10}

**Comment by robindhillon1** [comment]
Hi Glenn, thanks for your feedback. 
- Regarding the tests, I'm extremely disappointed in this as everything worked on our end but somehow this was overlooked. We will fix this asap.
- For the readme, the function is explicitly explained: `get_data: The function downloads all available historic price data for a selected stock and saves it. It utilizes the yfinance python package to automate the process.` The user can type in any stock and it will be downloaded, hence why we say downloads data for `selected stock`.

**Comment by robindhillon1** [comment]
We talked to Glenn during lab and everything seems to be fixed now. Closing issue.
