### ISSUE TITLE
License Decision

### ISSUE THREAD

**Issue by robindhillon1** [UBC-MDS/StockSignals#72]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories.

**Comment by RussDim** [comment]
I reveiwed the process for selecting a license on [choosealicense.com](choosealicense.com) as described during lecture.  Basically we need an open source license which should protect contributors and users.  If we need external contributors or plan to let others use this package, we should choose a license.  From past experience, I think the MIT license is a broadly used package, which is open to community use, is simple and permissive, and enables us to share our package with external parties.  What does the rest of the team think?

**Comment by wakesyracuse7** [comment]
I agree. MIT license is the most universal. I remember In the last 522 projects, my team has a thorough discussion about licenses. Because MIT allows users to reuse the code for any purpose, compared to the Apache license which consists much legal jargon, maybe it is more suitable to our project since our project is just a course project.

**Comment by robindhillon1** [comment]
Yes, I also think that we should stick to the MIT license due to the following reasons:
- As Dudu mentioned, the MIT license is one of the most popular and universal licenses around so lots of people are already familiar with it.
- Our project is open to the public and can be used by anyone since it is a learning tool. This allows people to gain knowledge and integrate/improve it as they desire, which is what this is really about.
- Liability and legal protection: we cannot be held accountable for anything that is connected to/is a consequence of our project. 

Due to such reasons, we should keep using the MIT license.

**Comment by pengzh313** [comment]
I agree we should keep our initial choice as the MIT license for this package:

First, there is no funding support or employment relationship pertaining to the development of this Python package. As the current UBC MDS students, we are following the DSCI 524 course instructions and voluntarily working on this team project for learning purposes only. In addition, as one of the authors, I have no any intention for economic interests from the package.

Second, as above mentioned, we welcome contributions from the public as per the specified contributing guidelines and Code of Conduct. The MIT license should be the best one suitable for this purpose.

Third, as Robin has already pointed out, by adopting MIT licence, it clearly states that there is no warranty from the package authors including us and future contributors. Users shall make their own judgement when using this package and no liabilities shall be assumed from us.

**Comment by robindhillon1** [comment]
Okay, it seems we are all in agreement that we should keep using the MIT license. For future reference, here's a link that explains the different licenses and why we end up choosing MIT: https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633#1-mit 
Closing this issue now.
